/**
 * Sample React Native App
 *
 * adapted from App.js generated by the following command:
 *
 * react-native init example
 *
 * https://github.com/facebook/react-native
 */

import React, { Component } from 'react';
import { Platform, StyleSheet, Text, View,Button, NativeModules } from 'react-native';
import Netspay from 'react-native-netspay';
import Axios from 'axios';

export default class App extends Component {
  state = {
    status: 'starting',
    message: '--'
  };
  componentDidMount() {
    Netspay.sampleMethod('Testing', 123, (message) => {
      this.setState({
        status: 'native callback received',
        message
      });
    });
    
  }

  pay = async()=>{
    var txn = {
      "ss":"1",
        "msg":{
              "txnAmount":"1000",
              "merchantTxnRef":"20170605 10:36:51.98",
              "b2sTxnEndURL":"https://sit2.enets.sg/MerchantApp/sim/b2sTxnEndURL.jsp",
              "s2sTxnEndURL":"https://sit2.enets.sg/MerchantApp/rest/s2sTxnEnd",
              "netsMid":"UMID_877772003",
              "merchantTxnDtm":"20170605 10:36:51.989",

              "mobileOs":"ANDROID",
              "submissionMode":"B",
              "paymentType":"SALE",
              "paymentMode":"",
              "clientType":"S",
      
              "currencyCode":"SGD",
              "merchantTimeZone":"+8:00",
              "language":"en", 
              "netsMidIndicator":"U",
              }
      }
      txn = JSON.stringify(txn)
    Axios.post('https://killy.saiva.in/payments/generate-hmac',{
      txn:txn
    })
    .then(async(res)=>{
      res = res.data
      console.log(res)
      var resp = await Netspay.makePayment({
        apiKey:'154eb31c-0f72-45bb-9249-84a1036fd1ca',
        txn : txn,
        hmac: res.toString()
      })
      console.log(resp)
    })


  }
  render() {
    return (
      <View style={styles.container}>
        <Text style={styles.welcome}>☆Netspay example☆</Text>
        <Text style={styles.instructions}>STATUS: {this.state.status}</Text>
        <Text style={styles.welcome}>☆NATIVE CALLBACK MESSAGE☆</Text>
        <Text style={styles.instructions}>{this.state.message}</Text>
        <Button title='pay' onPress={this.pay} />
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F5FCFF',
  },
  welcome: {
    fontSize: 20,
    textAlign: 'center',
    margin: 10,
  },
  instructions: {
    textAlign: 'center',
    color: '#333333',
    marginBottom: 5,
  },
});
